"""Synthetic spike-train and waveform generators.

This module is the single source of truth for the synthetic neural
data used by the example notebooks under ``examples/`` and by the
test suite under ``tests/``.  Before this module existed, every
notebook copy-pasted the same ~115 lines of Poisson-spike-and-
Gaussian-waveform setup, and ``tests/conftest.py`` carried its own
slightly different copy — three or four implementations of the same
idea, drifting out of sync any time someone touched one of them.

Public helpers
--------------
:func:`poisson_train`
    Bin-wise inhomogeneous Poisson process with an absolute
    refractory period.  Used by the notebooks to build per-trial
    spike trains with a tuning-curve-shaped rate profile.

:func:`make_tuned_spikes`
    Single Gaussian-tuned cluster — produces ``(spike_times, trials,
    angles, unique_angles)`` for one neuron with a chosen preferred
    direction.  Used by the tuning / statistics test fixtures.  Uses
    the simple per-trial ``rng.poisson`` + ``rng.uniform`` recipe so
    seeded test assertions stay stable.

:func:`make_two_unit_demo`
    Two-cluster "notebook demo" dataset — one orientation-indifferent
    unit and one orientation-selective unit, generated by
    :func:`poisson_train` with a bin-wise refractory period, plus
    Gaussian waveform templates.  Returns a :class:`TwoUnitDemo`
    NamedTuple containing every array the four example notebooks
    used to build inline (spike times, trials, angles, waveforms,
    ground-truth labels, plus a fully-loaded ``SortingData``).

Layering
--------
Notebooks ship through ``examples/`` and end-users open them
directly; they cannot rely on ``tests/conftest.py`` because
``tests/`` is not in the installed wheel
(``[tool.hatch.build.targets.wheel] packages = ["neural_cca"]``).
This module lives inside ``neural_cca/`` so both notebooks and the
test fixtures import from the same place.
"""

from __future__ import annotations

from typing import NamedTuple

import numpy as np
import numpy.typing as npt

from ._utils import make_rng, steps2degree
from .sorting.containers import SortingData
from .sorting.io_util import load_from_arrays

__all__ = [
    "poisson_train",
    "make_tuned_spikes",
    "make_two_unit_demo",
    "TwoUnitDemo",
]


# ---------------------------------------------------------------------------
# Low-level: bin-wise inhomogeneous Poisson with absolute refractory
# ---------------------------------------------------------------------------


def poisson_train(
    rng: np.random.Generator,
    rate_profile: npt.ArrayLike | float,
    dt: float,
    n_bins: int,
    refractory_s: float = 0.001,
) -> npt.NDArray[np.int64]:
    """Bin-wise inhomogeneous Poisson process with an absolute refractory.

    For each time bin ``b`` of width *dt*, draws a Bernoulli trial
    with probability ``rate(b) · dt``.  After a spike the next
    ``refractory_bins = max(1, int(refractory_s / dt))`` bins cannot
    fire — this is the *absolute* refractory contract, matching the
    convention used by the package's RPV / ACG analyses.

    Args:
        rng: ``numpy.random.Generator`` (or anything with
            ``.uniform()``).  Pass a seeded generator for
            reproducibility.
        rate_profile: Either a scalar (constant rate, Hz) or a
            length-``n_bins`` array of instantaneous rates (Hz).
        dt: Bin width in seconds.
        n_bins: Number of bins to simulate.
        refractory_s: Absolute refractory period in seconds
            (default 1 ms).  Set to 0 to disable.

    Returns:
        ``(n_spikes,)`` array of *bin indices* at which a spike
        fired.  Multiply by *dt* to get times in seconds.

    Notes:
        The implementation is a pure-Python loop because the
        refractory constraint couples consecutive bins; a vectorised
        Bernoulli draw followed by a refractory filter would
        overestimate the spike count whenever two would-be spikes
        fall within the refractory window.  For the typical use
        (25 kHz × 2.5 s × few hundred trials) this finishes in a
        few seconds — fine for one-shot demo construction.
    """
    p_spike = (
        np.asarray(rate_profile, dtype=np.float64) * dt
        if hasattr(rate_profile, "__len__")
        else np.full(n_bins, float(rate_profile) * dt)
    )
    refractory_bins = max(1, int(refractory_s / dt))
    spikes: list[int] = []
    last = -refractory_bins - 1
    for b in range(n_bins):
        if (b - last) > refractory_bins and rng.uniform() < p_spike[b]:
            spikes.append(b)
            last = b
    return np.array(spikes, dtype=np.int64)


# ---------------------------------------------------------------------------
# High-level: single orientation-tuned cluster
# ---------------------------------------------------------------------------


def make_tuned_spikes(
    preferred_angle: float = 90.0,
    n_angles: int = 12,
    n_repeats: int = 20,
    base_rate: float = 2.0,
    peak_rate: float = 30.0,
    sigma_deg: float = 30.0,
    trial_duration: float = 2.5,
    stimulus_onset: float = 0.5,
    rng: np.random.Generator | int | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Synthetic spike times from a Gaussian-tuned neuron.

    This is the test-friendly variant (``rng.poisson`` + ``rng.uniform``
    per trial) — the binwise refractory-enforcing path lives in
    :func:`make_two_unit_demo` via :func:`poisson_train`.  Keeping
    them separate means seeded test fixtures stay stable when the
    notebook helpers evolve.

    Args:
        preferred_angle: Peak of the Gaussian tuning curve (degrees).
        n_angles: Number of stimulus directions sampled evenly on
            360°.
        n_repeats: Repetitions per angle.
        base_rate: Spontaneous (pre-stimulus) firing rate in Hz.
        peak_rate: Maximum evoked firing rate at the preferred angle.
        sigma_deg: Width of the Gaussian tuning curve (degrees).
        trial_duration: Length of each trial in seconds.
        stimulus_onset: Time inside the trial where the stimulus
            starts (seconds).
        rng: Generator, integer seed, or ``None`` (default: seeded
            at 42 to match the historical fixture behaviour).

    Returns:
        ``(spike_times, trials, angles, unique_angles)``:

        - ``spike_times`` ``(n_spikes,)`` trial-relative times in s
        - ``trials`` ``(n_spikes,)`` 0-based trial index
        - ``angles`` ``(n_trials,)`` stimulus angle per trial
        - ``unique_angles`` ``(n_angles,)`` the distinct directions
    """
    # Default to seed=42 (not OS entropy) so this function reproduces
    # the historical test-fixture stream when called without a seed.
    if rng is None:
        rng = make_rng(42)
    else:
        rng = make_rng(rng)

    angles_deg = np.linspace(0, 360, n_angles, endpoint=False)
    angles = np.repeat(angles_deg, n_repeats)
    n_trials = len(angles)
    stim_duration = trial_duration - stimulus_onset

    all_st: list[npt.NDArray] = []
    all_tr: list[npt.NDArray] = []
    for t_idx in range(n_trials):
        ang = angles[t_idx]
        # Circular distance on the 360° direction circle.
        d = min(abs(ang - preferred_angle), 360 - abs(ang - preferred_angle))
        rate = base_rate + (peak_rate - base_rate) * np.exp(-(d**2) / (2 * sigma_deg**2))
        # Spontaneous (pre-stimulus) spikes.
        n_spont = rng.poisson(base_rate * stimulus_onset)
        spont_times = rng.uniform(0, stimulus_onset, n_spont)
        # Evoked (post-stimulus) spikes.
        n_evoked = rng.poisson(rate * stim_duration)
        evoked_times = rng.uniform(stimulus_onset, trial_duration, n_evoked)
        st = np.sort(np.concatenate([spont_times, evoked_times]))
        all_st.append(st)
        all_tr.append(np.full(len(st), t_idx, dtype=np.int64))

    spike_times = np.concatenate(all_st)
    trials = np.concatenate(all_tr)
    return spike_times, trials, angles, angles_deg


# ---------------------------------------------------------------------------
# High-level: two-cluster notebook demo
# ---------------------------------------------------------------------------


class TwoUnitDemo(NamedTuple):
    """Bundle of arrays produced by :func:`make_two_unit_demo`.

    Field order matches the variable names the original example
    notebooks used inline, so a notebook cell can do::

        from neural_cca.synthetic import make_two_unit_demo
        demo = make_two_unit_demo(seed=42)
        data = demo.sorting_data

    or unpack the legacy names explicitly when later cells still
    reference them by their old identifiers.

    Attributes:
        spike_times_c1, trials_c1: Cluster 1 (orientation-indifferent).
        spike_times_c2, trials_c2: Cluster 2 (orientation-selective).
        spike_times, trials, waveforms: Merged + chronologically
            sorted arrays — ready to pass to ``load_from_arrays``.
        ground_truth: Cluster ID (0/1) per spike, aligned with
            *spike_times* / *trials* / *waveforms*.
        angles: ``(n_trials,)`` stimulus angle per trial.
        n_trials, n_orientations, n_repeats: Stimulus protocol sizes.
        c2_pref_ori, c2_sigma: Tuning-curve parameters of cluster 2,
            re-exposed so downstream plots can annotate the truth.
        waveform_fs: Sampling rate used to bin the Poisson source
            (also stored on *sorting_data*).
        sorting_data: A fully-loaded :class:`SortingData` container
            equivalent to ``load_from_arrays(...)``.
        rng: The :class:`numpy.random.Generator` used during
            synthesis.  Returned so notebooks that add more noise
            downstream can continue from the same stream.
    """

    spike_times_c1: np.ndarray
    trials_c1: np.ndarray
    spike_times_c2: np.ndarray
    trials_c2: np.ndarray
    spike_times: np.ndarray
    trials: np.ndarray
    waveforms: np.ndarray
    ground_truth: np.ndarray
    angles: np.ndarray
    n_trials: int
    n_orientations: int
    n_repeats: int
    c2_pref_ori: float
    c2_sigma: float
    waveform_fs: float
    sorting_data: SortingData
    rng: np.random.Generator


def make_two_unit_demo(
    seed: np.random.Generator | int | None = 42,
    n_orientations: int = 12,
    n_repeats: int = 20,
    trial_duration: float = 2.5,
    stimulus_onset: float = 0.5,
    waveform_fs: float = 25_000.0,
    baseline_rate: float = 0.5,
    c1_stim_rate: float = 5.0,
    c2_max_rate: float = 10.0,
    c2_sigma: float = 15.0,
    c2_pref_ori: float = 90.0,
    refractory_s: float = 0.001,
    snippet_len: int = 48,
    noise_std: float = 0.3,
) -> TwoUnitDemo:
    """Build the canonical two-cluster spike-sorting demo dataset.

    Two synthetic neurons recorded on the same channel:

    * **Cluster 1** — orientation-indifferent, fires at
      *c1_stim_rate* (Hz) during the stimulus regardless of angle,
      with *baseline_rate* before stimulus onset.
    * **Cluster 2** — orientation-selective with a Gaussian tuning
      curve of width *c2_sigma* centred at *c2_pref_ori*.  Peak rate
      is *c2_max_rate* at the preferred angle, falling off to
      *baseline_rate* far from it.

    Both spike trains come from :func:`poisson_train` (binwise
    inhomogeneous Poisson with an absolute refractory of
    *refractory_s*).  Each cluster gets a Gaussian-template
    waveform plus per-spike Gaussian noise of standard deviation
    *noise_std*.  The two clusters are merged, sorted
    chronologically, and packaged into a :class:`SortingData`
    container so the result can be fed straight into
    :func:`neural_cca.run_sorting_pipeline`.

    Args:
        seed: Integer seed (default 42, matching the original
            notebook), an existing ``Generator``, or ``None`` for OS
            entropy.
        n_orientations: Number of distinct stimulus directions
            sampled evenly across 360°.
        n_repeats: Trials per direction.
        trial_duration: Length of each trial (seconds).  The stimulus
            occupies ``[stimulus_onset, trial_duration]``.
        stimulus_onset: When the stimulus turns on within a trial
            (seconds).
        waveform_fs: Sampling rate used both for the binwise Poisson
            and for the waveform x-axis (Hz).  25 kHz → 0.04 ms bins.
        baseline_rate, c1_stim_rate, c2_max_rate, c2_sigma,
            c2_pref_ori: Tuning-curve parameters (see docstring intro).
        refractory_s: Absolute refractory used by
            :func:`poisson_train` (seconds).
        snippet_len: Length of each waveform snippet (samples).
        noise_std: Per-sample Gaussian noise added to the waveform
            templates.

    Returns:
        :class:`TwoUnitDemo` — every array the example notebooks need.
    """
    rng = make_rng(seed)

    # ---- Stimulus protocol --------------------------------------
    n_trials = n_orientations * n_repeats
    angles_map = steps2degree(n_orientations)
    angles = np.array(
        [angles_map[(i % n_orientations) + 1] for i in range(n_trials)],
        dtype=np.float64,
    )

    # ---- Timing -------------------------------------------------
    dt = 1.0 / float(waveform_fs)
    n_bins = int(trial_duration / dt)
    time_axis = np.arange(n_bins) * dt
    pre_stim = time_axis < stimulus_onset

    # ---- Cluster 1: orientation-indifferent ---------------------
    spike_times_c1_list: list[np.ndarray] = []
    trials_c1_list: list[np.ndarray] = []
    for trial_idx in range(n_trials):
        rate = np.where(pre_stim, baseline_rate, c1_stim_rate)
        bins_fired = poisson_train(rng, rate, dt, n_bins, refractory_s=refractory_s)
        spike_times_c1_list.append(bins_fired * dt)
        trials_c1_list.append(np.full(len(bins_fired), trial_idx, dtype=np.int64))
    spike_times_c1 = np.concatenate(spike_times_c1_list)
    trials_c1 = np.concatenate(trials_c1_list)

    # ---- Cluster 2: orientation-selective -----------------------
    spike_times_c2_list: list[np.ndarray] = []
    trials_c2_list: list[np.ndarray] = []
    for trial_idx in range(n_trials):
        ori = angles[trial_idx]
        # Wrap to [0, 180) for orientation distance (period 180°).
        ori_diff = abs(ori - c2_pref_ori) % 180
        ori_diff = min(ori_diff, 180 - ori_diff)
        stim_rate = c2_max_rate * np.exp(-(ori_diff**2) / (2 * c2_sigma**2))
        rate = np.where(pre_stim, baseline_rate, stim_rate)
        bins_fired = poisson_train(rng, rate, dt, n_bins, refractory_s=refractory_s)
        spike_times_c2_list.append(bins_fired * dt)
        trials_c2_list.append(np.full(len(bins_fired), trial_idx, dtype=np.int64))
    spike_times_c2 = np.concatenate(spike_times_c2_list)
    trials_c2 = np.concatenate(trials_c2_list)

    # ---- Waveform snippets --------------------------------------
    t_wv = np.linspace(0, 1, snippet_len)
    # Cluster 1 template: sharp negative peak around sample 30 %.
    template_c1 = -4.0 * np.exp(-((t_wv - 0.3) ** 2) / 0.005)
    # Cluster 2 template: broader positive peak around sample 40 %.
    template_c2 = 2.0 * np.exp(-((t_wv - 0.4) ** 2) / 0.02)
    wv_c1 = template_c1[np.newaxis, :] + rng.normal(
        0.0, noise_std, (len(spike_times_c1), snippet_len)
    )
    wv_c2 = template_c2[np.newaxis, :] + rng.normal(
        0.0, noise_std, (len(spike_times_c2), snippet_len)
    )

    # ---- Merge + chronological sort -----------------------------
    spike_times = np.concatenate([spike_times_c1, spike_times_c2])
    trials = np.concatenate([trials_c1, trials_c2])
    waveforms = np.vstack([wv_c1, wv_c2])
    ground_truth = np.concatenate(
        [
            np.zeros(len(spike_times_c1), dtype=np.int64),
            np.ones(len(spike_times_c2), dtype=np.int64),
        ]
    )
    sort_idx = np.argsort(spike_times)
    spike_times = spike_times[sort_idx]
    trials = trials[sort_idx]
    waveforms = waveforms[sort_idx]
    ground_truth = ground_truth[sort_idx]

    sorting_data = load_from_arrays(
        waveforms=waveforms,
        spike_times=spike_times,
        trials=trials,
        angles=angles,
        waveform_fs=waveform_fs,
        stim_window=(stimulus_onset, trial_duration),
    )

    return TwoUnitDemo(
        spike_times_c1=spike_times_c1,
        trials_c1=trials_c1,
        spike_times_c2=spike_times_c2,
        trials_c2=trials_c2,
        spike_times=spike_times,
        trials=trials,
        waveforms=waveforms,
        ground_truth=ground_truth,
        angles=angles,
        n_trials=n_trials,
        n_orientations=n_orientations,
        n_repeats=n_repeats,
        c2_pref_ori=c2_pref_ori,
        c2_sigma=c2_sigma,
        waveform_fs=waveform_fs,
        sorting_data=sorting_data,
        rng=rng,
    )
